// רשימת המוזמנים — כל שורה = הזמנה אחת.
// last: שם משפחה (כמה שמות אפשר להפריד ב-"/", למשל "כהן / לוי")
// first: שמות פרטיים או "משפחת ..." (לא חובה)
// table: מספר השולחן
//
// דוגמה לשורה:
//   { last: "כהן", first: "משה ורחל", table: 12 },
//
// כל עוד הרשימה ריקה, האתר מציג הודעה שהסידור עוד לא פורסם.
window.GUESTS = [
  { last: "אבינערי", first: "מירית וירון", table: 4 },
  { last: "אברג'יל", first: "דוד", table: 1 },
  { last: "אברהם", first: "סער וזוהר", table: 15 },
  { last: "אגר", first: "דבי וחנני", table: 14 },
  { last: "אורן", first: "דקל", table: 1 },
  { last: "אינצי", first: "לירון", table: 6 },
  { last: "איפרגן", first: "עומרי", table: 5 },
  { last: "אלישיב", first: "אלונה וסם", table: 18 },
  { last: "אסיסקוביץ", first: "ירדן ותום", table: 8 },
  { last: "ארז", first: "רונית, הדר, שחר, שני, אופיר ועמית", table: 13 },
  { last: "אשל", first: "לילוש, גל ועוז", table: 18 },
  { last: "בארי", first: "עודד", table: 15 },
  { last: "בהרי", first: "ליאם", table: 20 },
  { last: "בוהנה", first: "שי", table: 5 },
  { last: "בויום", first: "תומר", table: 15 },
  { last: "ביטנסקי", first: "אמיר", table: 16 },
  { last: "בינימיני", first: "גלי", table: 7 },
  { last: "בן אהרון", first: "מיכל ונעמה", table: 2 },
  { last: "בן אהרון", first: "חגית ואלי", table: 3 },
  { last: "בן אהרון", first: "אלה, רעי, יאיר וגלי", table: 3 },
  { last: "בן יעקב", first: "נגה, יובל ופלג", table: 12 },
  { last: "בן יעקב", first: "נגה ואהוד", table: 14 },
  { last: "בן יעקב", first: "תמי, נרקיס, גפן, אלעד, רימון, עדי, שקד ואלמוג", table: 14 },
  { last: "בן יעקב", first: "יהודית וגיורא", table: 20 },
  { last: "בן יעקב", first: "מאירי ואורלי", table: 20 },
  { last: "בן יעקב", first: "עדי ואלונה", table: 20 },
  { last: "בר און", first: "מרב, יהודה, יונתן, נויה ועברי", table: 13 },
  { last: "בר אורין", first: "שקד", table: 9 },
  { last: "בר אילן", first: "יהלי", table: 16 },
  { last: "ברלס", first: "שרית", table: 4 },
  { last: "ברקוביץ", first: "יובל", table: 15 },
  { last: "גבריאל", first: "עופר וליבי", table: 11 },
  { last: "גולדפינגר", first: "אופירה ודובי", table: 11 },
  { last: "גולן", first: "ענבל", table: 9 },
  { last: "גור", first: "אמית ואסף", table: 7 },
  { last: "גור יעיש", first: "נורית", table: 6 },
  { last: "גינת", first: "דני", table: 1 },
  { last: "גינת", first: "רמי", table: 1 },
  { last: "גרשי", first: "רוני", table: 15 },
  { last: "דוברין", first: "יואב", table: 7 },
  { last: "דיין", first: "גל וסתיו", table: 16 },
  { last: "דינר", first: "טל", table: 5 },
  { last: "דניאל", first: "תלמה יוסי", table: 6 },
  { last: "דסקלו", first: "משה", table: 1 },
  { last: "הורוביץ", first: "ניצן", table: 15 },
  { last: "הלוי", first: "ניתאי", table: 16 },
  { last: "הראל", first: "אדוה", table: 12 },
  { last: "וויל", first: "עמוס ותמר", table: 19 },
  { last: "וויל", first: "אור ולאה", table: 19 },
  { last: "וויל", first: "תום ויעלי", table: 19 },
  { last: "וולק", first: "ליסה, עמית יובל, עידו ועלמה", table: 12 },
  { last: "ולרשטיין", first: "שרון", table: 11 },
  { last: "זוטא רז", first: "עינת", table: 7 },
  { last: "זיגל", first: "מאי וליה", table: 10 },
  { last: "זמיר", first: "אור", table: 15 },
  { last: "זפרן", first: "שחר", table: 10 },
  { last: "חלמיש", first: "שירי ובועז", table: 20 },
  { last: "חנה בן אהרון", first: "אפרת, דני, איל ואורי", table: 3 },
  { last: "טופז", first: "יובל", table: 20 },
  { last: "טל", first: "עמית וורוניקה", table: 10 },
  { last: "טלמור", first: "מלכי ואמיר", table: 5 },
  { last: "יהודית", first: "יהודית", table: 11 },
  { last: "יוחנן", first: "בברלי, אורי ומעיין", table: 7 },
  { last: "יניב", first: "גיל", table: 15 },
  { last: "כהן", first: "נדב", table: 9 },
  { last: "כנאני", first: "חוסאם", table: 5 },
  { last: "כעביה", first: "אסי", table: 5 },
  { last: "כץ", first: "רותי", table: 6 },
  { last: "כץ", first: "לילך", table: 11 },
  { last: "כץ זמיר", first: "אפרת", table: 6 },
  { last: "לאור", first: "אגם", table: 20 },
  { last: "לביא", first: "עמית בולק", table: 11 },
  { last: "לביא / פישמן", first: "דליה וקובי", table: 17 },
  { last: "לוגשי", first: "רמי", table: 13 },
  { last: "לוי", first: "לירז", table: 1 },
  { last: "לוי", first: "אורית, ג'ינג'י, מורן, רותם ועופרה", table: 2 },
  { last: "לוי", first: "אילת ועומר", table: 4 },
  { last: "לנדסברג", first: "אורי", table: 11 },
  { last: "לק", first: "איתן", table: 1 },
  { last: "מולי", first: "מולי", table: 15 },
  { last: "מונדייב", first: "ענבל ורני", table: 8 },
  { last: "מירון", first: "יעל", table: 3 },
  { last: "מלר", first: "מיכאל", table: 5 },
  { last: "מנור", first: "רועי, עירית, לטם, נדב, הדר ועידו", table: 18 },
  { last: "מרקוביץ", first: "יותם", table: 5 },
  { last: "נוסבאום", first: "ענבר", table: 5 },
  { last: "ניניו", first: "יובל", table: 9 },
  { last: "סבג", first: "עדי ונבו", table: 8 },
  { last: "סבג", first: "גלית", table: 8 },
  { last: "סדון", first: "שירה", table: 8 },
  { last: "סואעד", first: "איסלם", table: 5 },
  { last: "סולומון", first: "יאיר", table: 16 },
  { last: "סיגאווי", first: "ורד ושלומי", table: 2 },
  { last: "סיגאווי", first: "דוד", table: 2 },
  { last: "סיסו", first: "יורם", table: 1 },
  { last: "עוז", first: "דניאל", table: 9 },
  { last: "עידו", first: "בר", table: 9 },
  { last: "פטיטו", first: "טל", table: 16 },
  { last: "פישמן", first: "פרדי, גבי, שי, גל ותום", table: 17 },
  { last: "פישמן", first: "אריה וקרן", table: 17 },
  { last: "פישמן", first: "תמי ועודד", table: 19 },
  { last: "פלינק", first: "איתמר ומאיה", table: 10 },
  { last: "פנחס", first: "סהר וניצן", table: 10 },
  { last: "פרץ", first: "בר", table: 1 },
  { last: "צפריר", first: "שי", table: 6 },
  { last: "קדוש", first: "דבש", table: 9 },
  { last: "קומר", first: "איילת ועודד", table: 7 },
  { last: "קומר", first: "מאיה", table: 9 },
  { last: "קוסק", first: "אביה וגיא", table: 8 },
  { last: "קיוי", first: "ליבי", table: 15 },
  { last: "קירזנר", first: "אוסנת, רונן ושחר", table: 12 },
  { last: "קליגר", first: "רחלי, עודד, אופיר ואמיר", table: 4 },
  { last: "קליין", first: "יעלה, אבנר ניר וגל", table: 6 },
  { last: "קפל", first: "אופיר ואליאור", table: 16 },
  { last: "רביי", first: "פסח", table: 1 },
  { last: "רובין", first: "אבישג", table: 10 },
  { last: "רוס וויס", first: "אלירז", table: 11 },
  { last: "רינגר", first: "יאיר ושיר", table: 16 },
  { last: "רקדזון", first: "מעיין", table: 16 },
  { last: "שחם", first: "חגי", table: 11 },
  { last: "שניצר", first: "תמר", table: 15 },
  { last: "שפר", first: "תמר ונועם", table: 9 },
  { last: "שרגורודסקי", first: "גיא", table: 10 },
  { last: "שריפיאן / קוסק", first: "אראלה ומיה", table: 8 },
  { last: "תדמור", first: "מוניק", table: 5 },
];
